const IMPORT_TEXT = 'Importuj';
const PERIOD_TEXT = 'Zapisz';
const CALCULATE_TEXT = 'Oblicz';
const DELETE_ITEM_TEXT = 'Usuń';
const ACCEPT_TEXT = 'Zatwierdź';

export default {
    IMPORT_TEXT: IMPORT_TEXT,
    PERIOD_TEXT: PERIOD_TEXT,
    CALCULATE_TEXT: CALCULATE_TEXT,
    DELETE_ITEM_TEXT: DELETE_ITEM_TEXT,
    ACCEPT_TEXT: ACCEPT_TEXT
}
